import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { defineConfig, loadEnv, type Plugin } from "vite";

const root = import.meta.dirname;

/** Host config in public/, served by the host but never requested by the app. */
const NOT_PRECACHED = new Set(["/_headers"]);

/** Every file under public/, as site paths ("/icons/icon-192.png"). */
function publicFiles(dir = join(root, "public")): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? publicFiles(join(dir, entry.name))
      : [`/${relative(join(root, "public"), join(dir, entry.name)).split("\\").join("/")}`],
  );
}

/**
 * Emits sw.js with the exact list of built files to precache, so the app works offline
 * from the first visit. The cache name is a hash of every file's path and contents, so any change makes
 * the new worker replace the old cache on the next visit.
 */
function serviceWorker(): Plugin {
  return {
    name: "azkar-guard-service-worker",
    apply: "build",
    generateBundle(_, bundle) {
      const assets = ["/", ...Object.keys(bundle).map((f) => `/${f}`), ...publicFiles().filter((f) => !NOT_PRECACHED.has(f))];
      const hash = createHash("sha256");
      for (const file of Object.values(bundle)) {
        hash.update(file.fileName).update(file.type === "chunk" ? file.code : file.source);
      }
      for (const file of publicFiles()) hash.update(file).update(readFileSync(join(root, "public", file)));
      const version = hash.digest("hex").slice(0, 12);
      const source = `// Generated by vite.config.ts. Precaches the app shell; serves it cache-first.
const CACHE = "azkar-guard-${version}";
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;
  // Navigations always get the app shell: the app routes by hash.
  const key = request.mode === "navigate" ? "/" : request;
  event.respondWith(caches.match(key).then((hit) => hit ?? fetch(request)));
});

// Reminders from azkar-guard-api. The payload is { session, key, lang }; the text lives here.
const TEXT = {
  en: {
    morning: "Morning Azkar not finished yet",
    evening: "Evening Azkar not finished yet",
    bodies: [
      "Tap to open your checklist.",
      "It takes only a few minutes… and the Azkar are the Muslim's fortress.",
      "“Remember Me; I will remember you.” (2:152)",
    ],
  },
  ar: {
    morning: "لم تُتمّ أذكار الصباح بعد",
    evening: "لم تُتمّ أذكار المساء بعد",
    bodies: [
      "اضغط لفتح الأذكار.",
      "لن تأخذ إلا دقائق… والأذكار حصن المسلم.",
      "«فَاذْكُرُونِي أَذْكُرْكُمْ»",
    ],
  },
};

self.addEventListener("push", (event) => {
  let data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch {}
  const text = TEXT[data.lang === "ar" ? "ar" : "en"];
  // Vary the body each half hour so repeated reminders don't all look the same.
  const body = text.bodies[Math.floor(Date.now() / 1800000) % text.bodies.length];
  event.waitUntil(
    self.registration.showNotification(data.session === "evening" ? text.evening : text.morning, {
      body,
      icon: "/icons/icon-192.png",
      tag: data.key || "azkar-guard",
      renotify: true,
      lang: data.lang === "ar" ? "ar" : "en",
      dir: data.lang === "ar" ? "rtl" : "ltr",
    }),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((windows) => {
      const open = windows.find((w) => new URL(w.url).origin === self.location.origin);
      if (open) return open.focus();
      return self.clients.openWindow("/");
    }),
  );
});
`;
      this.emitFile({ type: "asset", fileName: "sw.js", source });
    },
  };
}

/** Lets the page call the reminders API: adds its origin to the CSP's connect-src. */
function apiCsp(apiUrl: string | undefined): Plugin {
  const origin = apiUrl ? new URL(apiUrl).origin : "";
  return {
    name: "azkar-guard-api-csp",
    transformIndexHtml: (html) => html.replace("connect-src 'self'", `connect-src 'self'${origin ? ` ${origin}` : ""}`),
  };
}

export default defineConfig(({ mode }) => ({
  plugins: [serviceWorker(), apiCsp(loadEnv(mode, root).VITE_API_URL)],
  build: {
    outDir: "dist",
    emptyOutDir: true,
    target: "es2022",
  },
}));
