import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { defineConfig, type Plugin } from "vite";

const root = import.meta.dirname;

/** Host config in public/, served by the host but never requested by the app. */
const NOT_PRECACHED = new Set(["/_headers"]);

/** Every file under public/, as site paths ("/icons/icon-192.png"). */
function publicFiles(dir = join(root, "public")): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? publicFiles(join(dir, entry.name))
      : [`/${relative(join(root, "public"), join(dir, entry.name)).split("\\").join("/")}`],
  );
}

/**
 * Emits sw.js with the exact list of built files to precache, so the app works offline
 * from the first visit. The cache name is a hash of every file's path and contents, so any change makes
 * the new worker replace the old cache on the next visit.
 */
function serviceWorker(): Plugin {
  return {
    name: "azkar-guard-service-worker",
    apply: "build",
    generateBundle(_, bundle) {
      const assets = ["/", ...Object.keys(bundle).map((f) => `/${f}`), ...publicFiles().filter((f) => !NOT_PRECACHED.has(f))];
      const hash = createHash("sha256");
      for (const file of Object.values(bundle)) {
        hash.update(file.fileName).update(file.type === "chunk" ? file.code : file.source);
      }
      for (const file of publicFiles()) hash.update(file).update(readFileSync(join(root, "public", file)));
      const version = hash.digest("hex").slice(0, 12);
      const source = `// Generated by vite.config.ts. Precaches the app shell; serves it cache-first.
const CACHE = "azkar-guard-${version}";
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;
  // Navigations always get the app shell: the app routes by hash.
  const key = request.mode === "navigate" ? "/" : request;
  event.respondWith(caches.match(key).then((hit) => hit ?? fetch(request)));
});
`;
      this.emitFile({ type: "asset", fileName: "sw.js", source });
    },
  };
}

export default defineConfig({
  plugins: [serviceWorker()],
  build: {
    outDir: "dist",
    emptyOutDir: true,
    target: "es2022",
  },
});
